### ISSUE TITLE
A couple of changes to readme.md and statsd issue if Grafana is installed

### ISSUE THREAD

**Issue by creinemann** [JVital2013/vitality-goes#10]
I have had some folks write me with a few problems they have had during setup:
One is that many already have Grafana setup and running for system data, the statsd is already allocated, a fix is needed for this to avoid have to remove grafana, otherwise and error is generated - `port 8125:8125 is in use:`
```
[monitor]
statsd_address = "udp4://localhost:8125"
```

Syntax here might me to change this line in the readme.md

**"That's it! To verify it's working, go to http://graphitehost:8080/ and make sure you see something that looks like this:"**

to this-

**"That's it! To verify it's working, go to http://deviceIPaddress:8080/ (example HTTP://192.168.1.24:8080) and make sure you see something that looks like this:"**

**Comment by JVital2013** [comment]
Clarified wording in commit ca3148d. The core of this issue (conflict between Graphite and Grafana) is being tracked over in #9 so I'm closing this for now.
