### ISSUE TITLE
Getting some error using CreateVideos scripts

### ISSUE THREAD

**Issue by pumatrax** [JVital2013/vitality-goes#16]
Hey,

I understand I might not have a weeks worth of data but I tried running the CreateVideos scripts and for the ENWIN this is the output.

`pi@hampi:~/vitality-goes/scripts $ ./CreateVideos-EMWIN.sh 
[2022-06-23 17:44:59] Creating LocalRadar...
mogrify-im6.q16: unable to open image `*.GIF': No such file or directory @ error/blob.c/OpenBlob/2924.
rm: cannot remove '*.GIF': No such file or directory
[image2 @ 0x1448b50] Could not open file : *.png
Output file #0 does not contain any stream
[2022-06-23 17:45:00] Creating USRadar...
mogrify-im6.q16: unable to open image `*.GIF': No such file or directory @ error/blob.c/OpenBlob/2924.
rm: cannot remove '*.GIF': No such file or directory
[image2 @ 0x1720b50] Could not open file : *.png
Output file #0 does not contain any stream
[2022-06-23 17:45:00] Creating HIMAWARI8...
mogrify-im6.q16: unable to open image `*.GIF': No such file or directory @ error/blob.c/OpenBlob/2924.
rm: cannot remove '*.GIF': No such file or directory
[image2 @ 0x7acb50] Could not open file : *.png
Output file #0 does not contain any stream
[2022-06-23 17:45:01] Creating GOES16EMWIN...
[image2 @ 0x66eb50] Could not open file : *.JPG
Output file #0 does not contain any stream
[2022-06-23 17:45:02] Creating GOES17EMWIN...
[image2 @ 0x1f5cb50] Could not open file : *.JPG
Output file #0 does not contain any stream
[2022-06-23 17:45:03] Creating METEOSAT...
[image2 @ 0x2304b50] Could not open file : *.JPG
Output file #0 does not contain any stream
[2022-06-23 17:45:04] Done!
pi@hampi:~/vitality-goes/scripts $ `

Here is part of the config:
`#!/bin/bash
srcDir="/media/SDCARD/emwin"
videoDir="/var/www/html/videos"
codeName=("RADNTHES" "RADREFUS" "GMS008JA" "G16CIRUS" "G10CIRUS" "INDCIRUS")
videoName=("LocalRadar" "USRadar" "HIMAWARI8" "GOES16EMWIN" "GOES17EMWIN" "METEOSAT")
imgconvert=("GIF" "GIF" "GIF" "JPG" "JPG" "JPG")`

I also noticed this is part of the script. Does anything need to be changed here, its pointing to a home/jamie folder? 

`for dateStamp in `seq $oneDayStartTime $oneDayEndTime`
	do
		cp /home/jamie/Desktop/sdr-recordings/emwin/*_$dateStamp*${codeName[$i]}.${imgconvert[$i]} .  > /dev/null 2>&1
	done`

**Comment by JVital2013** [comment]
Do you have dated subdirectories within your product folders? For example, do you have folders that look like 2022-06-22, 2022-06-23, etc in your emwin folder? If so, that's the problem. The scripts need updated to support dated subfolders - a bit of an oversight on my part. This is being tracked over in #13.

Honestly, the video scripts need blown up and started over. They only work in some circumstances. It's low on my priority list right now but I'll probably get around to it eventually.

If anyone wants to rework the video rendering scripts before I get to gem, I'm open to pull requests

**Comment by pumatrax** [comment]
Hi, no dated folders anymore. I used your goesproc as I caught that part. I'm not much of a programmer so i'll keep an eye out for future updates. I did see a comment where you said it works for you lol.  

I think the sanchez script works a little but I get an error at the GOES16/17 Composite.

pi@hampi:~/vitality-goes/scripts $ sudo ./Sanchez.sh 
[2022-06-23 21:34:45] Creating GOES 16 Sanchez False Color Images
[2022-06-23 21:34:46] Creating GOES 17 Sanchez False Color Images
[2022-06-23 21:34:47] Creating GOES 16/17 Composite False Color Images
date: invalid date ‘ :: UTC + 15 minutes’
date: invalid date ‘ :: UTC - 15 minutes’
[2022-06-23 21:34:47] Creating /media/SDCARD/composite/goes16_17_composite_20220622T235031Z.jpg...
Error: Can't create /tmp/underlay.jpg.
Exiting from DisplayOutput.cpp at line 69
Sanchez 1.0.19
Copyright (C) 2022 Matt Painter

ERROR(S):
  Option '::' is unknown.
  Option 'T, timestamp' has no value.

**Comment by pumatrax** [comment]
I am just having a problem with the ENWIN. What can I check? 

pi@hampi:~/vitality-goes/scripts $ sudo ./CreateVideos-EMWIN.sh 
[2022-06-24 17:25:50] Creating LocalRadar...
mogrify-im6.q16: unable to open image `*.GIF': No such file or directory @ error/blob.c/OpenBlob/2924.
rm: cannot remove '*.GIF': No such file or directory
[image2 @ 0x111fb50] Could not open file : *.png
Output file #0 does not contain any stream
[2022-06-24 17:25:51] Creating USRadar...
mogrify-im6.q16: unable to open image `*.GIF': No such file or directory @ error/blob.c/OpenBlob/2924.
rm: cannot remove '*.GIF': No such file or directory
[image2 @ 0x24b8b50] Could not open file : *.png
Output file #0 does not contain any stream
[2022-06-24 17:25:52] Creating HIMAWARI8...
mogrify-im6.q16: unable to open image `*.GIF': No such file or directory @ error/blob.c/OpenBlob/2924.
rm: cannot remove '*.GIF': No such file or directory
[image2 @ 0x530b50] Could not open file : *.png
Output file #0 does not contain any stream
[2022-06-24 17:25:53] Creating GOES16EMWIN...
[image2 @ 0x22b1b50] Could not open file : *.JPG
Output file #0 does not contain any stream
[2022-06-24 17:25:54] Creating GOES17EMWIN...
[image2 @ 0x22fcb50] Could not open file : *.JPG
Output file #0 does not contain any stream
[2022-06-24 17:25:55] Creating METEOSAT...
[image2 @ 0x1ae8b50] Could not open file : *.JPG
Output file #0 does not contain any stream
[2022-06-24 17:25:56] Done!

**Comment by pumatrax** [comment]
I think I figured it out. I had to change this location to point to my ENWIN folder. 

for dateStamp in `seq $oneDayStartTime $oneDayEndTime`
	do
		cp /media/SDCARD/emwin/*_$dateStamp*${codeName[$i]}.${imgconvert[$i]} .  > /dev/null 2>&1
	done

you had it set to /home/pi/jamie/Desktop...

**Comment by JVital2013** [comment]
Yep, that was fixed in 9e59285. I'll make a new release so people don't accidentally download the old one. Are you still having issues with other scripts or do you have them all working for now?

**Comment by pumatrax** [comment]
It looks like it's all working now. Thank you for such a wonderful project.
