### ISSUE TITLE
Local Weather Info

### ISSUE THREAD

**Issue by ve3elb** [JVital2013/vitality-goes#51]
Trying to setup the local weather page for buffalo new york but when I put the info I got from the websites I get errors anyone can help with the correct info. thank you

![Capture2](https://github.com/JVital2013/vitality-goes/assets/89200343/fa5e89fc-085f-487a-b962-f4af572315ea)
![Capture3](https://github.com/JVital2013/vitality-goes/assets/89200343/fba79899-1a3f-4bc1-8e39-66a9ff9b8d00)

**Comment by ve3elb** [comment]
@JVital2013  Thank You very much. Am in Toronto Canada so buffalo is the closest to my. however I still want to add that generic Canadian weather info you told me about but I don't remember where and how it has to be done.. Thank You for all your help

**Comment by JVital2013** [comment]
On the "Other EMWIN" screen, it looks like there are a number of products that contain Toronto. I'll put screenshots of their configs here.

![image](https://github.com/JVital2013/vitality-goes/assets/24253715/a6df84d6-41ec-4176-8e87-ab3372722141)
![image](https://github.com/JVital2013/vitality-goes/assets/24253715/7f383798-9956-4030-be9e-5153a8b4bb4f)
![image](https://github.com/JVital2013/vitality-goes/assets/24253715/8944266b-5e00-4319-af1e-b9d12ed899ed)

**Comment by ve3elb** [comment]
@JVital2013  How can I add this to the other emwin.ini file. I tried duplicating one of the settings but no luck.

**Comment by JVital2013** [comment]
This will do it:

```ini
[NATEMP]
identifier = "TCPNAMUS"
title = "North American Temps"
format = formatted
truncate = 3

[UVINFO]
identifier = "UVIWAOCN"
title = "UV Information"
format = formatted
truncate = 4

[GATEWAYOBS]
identifier = "OPUCHSSC"
title = "[Test] KCHS/KSAV Gateway Observations"
format = formatted
truncate = 3
```
