### ISSUE TITLE
Typo in abi.ini

### ISSUE THREAD

**Issue by burgeda** [JVital2013/vitality-goes#66]
Incredibly minor typo in abi.ini  in the satdump-goes16 folder.  Didn't check the other sats.
In the section for channel 7 enhanced,  the word "enhanced" has a typo.

Line 71
"videoPath = GOES16Ch7Enchanced.mp4"

should be

videoPath = GOES16Ch7Enhanced.mp4

**Comment by JVital2013** [comment]
Good catch, thanks!
