### ISSUE TITLE
Current weather not displaying properly. 

### ISSUE THREAD

**Issue by ImDroided** [JVital2013/vitality-goes#68]
My local weather is not displaying correct. What did I break lol? Not sure how long it has been like this as I was away and not checking it for a while. 

It is 69F outside right now. 

![image](https://github.com/JVital2013/vitality-goes/assets/13988713/40cf72ae-8bc9-44ef-afd3-c2b468c4e623)

**Comment by JVital2013** [comment]
I can reproduce this - definitely a bug. I'll let you know when it's fixed!

**Comment by JVital2013** [comment]
This is now fixed on the main branch. Thanks for reporting it!

![image](https://github.com/JVital2013/vitality-goes/assets/24253715/f78c4072-9d3f-4149-87e1-1817053878cc)
